;this file for FamiTone2 library generated by text2data tool

PongMusic_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$cf,$cb,$c9,$c7,$c6,$c5,$c4,$00,$07
@env2:
	.byte $c3,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$00,$07


@song0ch0:
	.byte $fb,$06
@ref0:
	.byte $82,$33,$37,$80,$41,$82,$33,$37,$80,$40,$85,$82,$30,$85,$37,$80
	.byte $41,$82,$33,$37,$80,$40,$89
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
@song0ch0loop:
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $ff,$0f
	.word @ref0
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref16:
	.byte $bf
@ref17:
	.byte $bf
@ref18:
	.byte $bf
@ref19:
	.byte $bf
@ref20:
	.byte $80,$02,$ad,$0a,$8d
@ref21:
	.byte $02,$00,$82,$02,$00,$80,$02,$00,$82,$02,$00,$80,$02,$00,$82,$02
	.byte $00,$83,$80,$06,$00,$83,$06,$00,$82,$06,$00,$80,$07,$01,$0a,$89
@ref22:
	.byte $02,$ad,$0a,$8d
	.byte $ff,$18
	.word @ref21
@song0ch1loop:
	.byte $ff,$04
	.word @ref20
	.byte $ff,$18
	.word @ref21
@ref26:
	.byte $02,$ad,$0a,$8d
	.byte $ff,$18
	.word @ref21
@ref28:
	.byte $02,$ad,$0a,$8d
	.byte $ff,$18
	.word @ref21
@ref30:
	.byte $bf
@ref31:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref32:
	.byte $bf
@ref33:
	.byte $bf
@ref34:
	.byte $bf
@ref35:
	.byte $bf
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
@song0ch2loop:
@ref40:
	.byte $82,$4a,$4e,$4a,$a9,$4a,$4e,$4a,$85,$40,$81
@ref41:
	.byte $87,$3c,$3a,$40,$b1
@ref42:
	.byte $4a,$4e,$4a,$a9,$4a,$4e,$4a,$85,$40,$81
	.byte $ff,$05
	.word @ref41
@ref44:
	.byte $4a,$4e,$58,$a9,$4a,$4e,$58,$85,$52,$81
@ref45:
	.byte $01,$52,$85,$4f,$52,$ad
	.byte $ff,$0a
	.word @ref44
	.byte $ff,$06
	.word @ref45
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref48:
	.byte $00,$bd
@ref49:
	.byte $bf
@ref50:
	.byte $82,$17,$17,$16,$85,$17,$80,$13,$01,$82,$16,$85,$17,$16,$85,$17
	.byte $80,$13,$01,$82,$12,$81
@ref51:
	.byte $17,$17,$16,$85,$17,$80,$13,$01,$82,$16,$85,$17,$16,$85,$17,$80
	.byte $13,$01,$82,$12,$81
	.byte $ff,$11
	.word @ref51
	.byte $ff,$11
	.word @ref51
	.byte $ff,$11
	.word @ref51
	.byte $ff,$11
	.word @ref51
@song0ch3loop:
	.byte $ff,$11
	.word @ref50
	.byte $ff,$11
	.word @ref51
	.byte $ff,$11
	.word @ref51
	.byte $ff,$11
	.word @ref51
	.byte $ff,$11
	.word @ref51
	.byte $ff,$11
	.word @ref51
@ref62:
	.byte $00,$bd
@ref63:
	.byte $bf
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref64:
	.byte $bf
@ref65:
	.byte $bf
@ref66:
	.byte $bf
@ref67:
	.byte $bf
@ref68:
	.byte $bf
@ref69:
	.byte $bf
@ref70:
	.byte $bf
@ref71:
	.byte $bf
@song0ch4loop:
@ref72:
	.byte $bf
@ref73:
	.byte $bf
@ref74:
	.byte $bf
@ref75:
	.byte $bf
@ref76:
	.byte $bf
@ref77:
	.byte $bf
@ref78:
	.byte $bf
@ref79:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
